name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Fetch the main repository
      - name: Fetch main repository
        run: |
          git remote add upstream https://github.com/Yidnekachew-cmd/ezra-test-backend.git
          git fetch upstream

      # Install Digital Ocean CLI
      - name: Install Digital Ocean CLI
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/download/v1.75.0/doctl-1.75.0-linux-amd64.tar.gz | tar -xzv
          sudo mv doctl /usr/local/bin

      # Authenticate with Digital Ocean
      - name: Authenticate with Digital Ocean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          doctl auth init -t $DO_API_TOKEN

      # Compare changes with main repo
      - name: Compare changes
        run: |
          # Check for changes
          git diff upstream/main..HEAD --name-only

          # If there are changes, deploy them
          if [ -n "$(git diff upstream/main..HEAD --name-only)" ]; then
            echo "Changes detected, deploying to Digital Ocean..."

            # Build and test the application
            npm ci

            # Deploy the application
            doctl apps update ezra-test-backend --wait
          else
            echo "No changes detected, skipping deployment."
          fi
